[WIP] Created more account and accountclaim conditions
openshift/aws-account-operator pull request #485
Opened 2020-10-07 18:04 UTC by ArielLima

Each existing code path that leads to a failed account has a new, representative condition with a descriptive TYPE, REASON and MESSAGE.

Card -> https://issues.redhat.com/browse/OSD-5396

2020-10-13 17:20 UTC, clcollins requested changes

2020-10-13 17:20 UTC, clcollins commented on pkg/apis/aws/v1alpha1/account_types.go
> +	// AccountCreationFailed is set when an error occured during account creations
Would you mind making this "...during AWS account creation" to specify that it was a "real" account creation that failed, and not our operator CR object that failed?  Just to be clear what the difference is until the "AccountFailed" condition goes away.

2020-10-26 19:40 UTC, rogbas commented
@ArielLima there is some lint and build errors, could you please check it? thanks

2020-10-29 19:14 UTC, ArielLima commented
/retry

2020-11-02 17:42 UTC, ArielLima commented
/retry

2020-11-11 16:25 UTC, rogbas commented
/lgtm
/approve

2020-11-11 16:41 UTC, merged