Improve STS related docs
openshift/aws-account-operator pull request #576
Opened 2021-05-11 15:59 UTC by dastergon

After some troubleshooting around STS, I realized that some areas need an update to reflect the latest STS changes. 
I updated the configmap generation script and the docs.

Needs #574 to be merged first

PTAL

2021-05-12 19:01 UTC, iamkirkbater requested changes

2021-05-12 19:01 UTC, iamkirkbater commented on docs/1.0-Installation.md
> +    .hack/scripts/set_operator_configmap.sh -a ${ACCOUNT_LIMIT} -v ${VCPU_QUOTA} -r "${OSD_STAGING_1_OU_ROOT_ID}" -o "${OSD_STAGING_1_OU_BASE_ID}" -s ${AWS_ARN}
Using the env vars that you've set in the README, wouldn't this be `-s ${STS_JUMP_ROLE_ARN}`

2021-05-14 12:47 UTC, dastergon commented
@iamkirkbater I've updated the PR with your suggestions! Thanks :) PTAL

2021-05-14 13:47 UTC, dastergon commented
/test images

2021-05-14 14:00 UTC, iamkirkbater commented
This looks great!  Feel free to remove the hold on monday after #574 is merged and let this one merge in.

/lgtm
/hold

2021-05-14 14:00 UTC, iamkirkbater commented
/approve

2021-05-18 07:45 UTC, dastergon commented
/hold cancel

2021-05-18 07:45 UTC, merged