probe secret
openshift/aws-account-operator pull request #678
Opened 2022-02-28 16:05 UTC by katherinelc321

This PR probes the osd-admin secret in accounts and heal them if they're invalid https://issues.redhat.com/browse/OSD-9298

2022-03-03 14:17 UTC, dkeohane commented on config/config.go
> +func SetHiveSHardName(configMap *corev1.ConfigMap) error {
```suggestion
func SetHiveShardName(configMap *corev1.ConfigMap) error {
```

2022-03-03 14:18 UTC, dkeohane commented on cmd/manager/main.go
> +	// Define a kubeClient for any processes that need to run during operator startup or independent routines to use
From: https://github.com/openshift/aws-account-operator/pull/668#discussion_r810034883
```suggestion
	// Define a kubeClient for any processes that need to run during operator startup or independent routines to use
	// We should avoid using this kubeClient except for when necessary and utilize the operator-sdk provided client as much as possible.
	// The operator-sdk kube client provides a level of caching that we don't get with building our own this way.
```

2022-03-03 14:22 UTC, iamkirkbater requested changes

2022-03-03 14:22 UTC, iamkirkbater commented on config/config.go
> +func SetHiveShardName(configMap *corev1.ConfigMap) error {
I don't see where we're calling this.  I think we need to explicitly call this in manager.go first.

2022-03-17 20:58 UTC, iamkirkbater requested changes
This breaks during STS testing. `make test-sts` was able to catch this.  `make test-integration` runs through all of our integration tests.

Here's a patch of the changes I made to get this working:
```
diff --git a/pkg/controller/account/account_controller.go b/pkg/controller/account/account_controller.go
index 3b1220f4..1975f77b 100644
--- a/pkg/controller/account/account_controller.go
+++ b/pkg/controller/account/account_controller.go
@@ -344,11 +344,6 @@ func (r *ReconcileAccount) Reconcile(request reconcile.Request) (reconcile.Resul
 	}
 	regionAMIs := processConfigMapRegions(stringRegions)
 
-	awsAssumedRoleClient, creds, err := r.handleCreateAdminAccessRole(reqLogger, currentAcctInstance, awsSetupClient)
-	if err != nil {
-		return reconcile.Result{}, err
-	}
-
 	// Account init for both BYOC and Non-BYOC
 	if currentAcctInstance.ReadyForInitialization() {
 		reqLogger.Info("initializing account", "awsAccountID", currentAcctInstance.Spec.AwsAccountID)
@@ -397,6 +392,11 @@ func (r *ReconcileAccount) Reconcile(request reconcile.Request) (reconcile.Resul
 			return reconcile.Result{Requeue: true}, r.Client.Update(context.TODO(), currentAcctInstance)
 		}
 
+		awsAssumedRoleClient, creds, err := r.handleCreateAdminAccessRole(reqLogger, currentAcctInstance, awsSetupClient)
+		if err != nil {
+			return reconcile.Result{}, err
+		}
+
 		// Use the same ID applied to the account name for IAM usernames
 		iamUserUHC := fmt.Sprintf("%s-%s", iamUserNameUHC, currentAcctInstance.Labels[awsv1alpha1.IAMUserIDLabel])
 		secretName, err := r.BuildIAMUser(reqLogger, awsAssumedRoleClient, currentAcctInstance, iamUserUHC, request.Namespace)
@@ -430,14 +430,27 @@ func (r *ReconcileAccount) Reconcile(request reconcile.Request) (reconcile.Resul
 	}
 
 	if currentAcctInstance.IsReady() {
+		roleToAssume := getAssumeRole(currentAcctInstance)
+		awsClient, _, err := r.assumeRole(reqLogger, currentAcctInstance, awsSetupClient, roleToAssume, "")
+		if err != nil {
+			reqLogger.Error(err, "failed building BYOC client from assume_role")
+			// We don't want to error here as erroring will requeue and we will end in an
+			// infinite loop.  So we just log the error and exit.
+			// TODO maybe there's a better way to handle this?
+			return reconcile.Result{}, nil
+		}
 
 		// Check that secret is valid and reheal it if not
 		iamUserUHC := fmt.Sprintf("%s-%s", iamUserNameUHC, currentAcctInstance.Labels[awsv1alpha1.IAMUserIDLabel])
 
 		reqLogger.Info("probing account secret")
-		err := r.ProbeSecret(reqLogger, currentAcctInstance, awsAssumedRoleClient, iamUserUHC, request.Namespace)
+		err = r.ProbeSecret(reqLogger, currentAcctInstance, awsClient, iamUserUHC, request.Namespace)
 		if err != nil {
-			return reconcile.Result{}, err
+			reqLogger.Error(err, "failed to probe secret")
+			// We don't want to error here as erroring will requeue and we will end in an
+			// infinite loop.  So we just log the error and exit.
+			// TODO maybe there's a better way to handle this?
+			return reconcile.Result{}, nil
 		}
 	}
 
```

2022-03-17 20:58 UTC, iamkirkbater commented on pkg/controller/account/account_controller.go
> +
Is there a reason this got moved up?  This seems to be breaking STS cluster initialization.

2022-03-17 20:58 UTC, iamkirkbater commented on pkg/controller/account/account_controller.go
> +
Ahh, figured it out.  Patch included in review comment.

2022-03-29 15:55 UTC, iamkirkbater commented
/lgtm

2022-03-29 16:08 UTC, merged