Preview gosec lint rule
openshift/aws-account-operator pull request #685
Opened 2022-03-24 16:10 UTC by 2uasimojo

2022-03-24 16:11 UTC, 2uasimojo commented
cf. https://github.com/openshift/boilerplate/pull/206

2022-03-31 20:37 UTC, fahlmant requested changes
Please provide a description

2022-03-31 21:03 UTC, 2uasimojo commented
> Please provide a description

Yah, sorry, I was just throwing this out as an example pursuant to https://github.com/openshift/boilerplate/pull/206#issuecomment-1077797612

Added description.

2022-04-06 08:17 UTC, dastergon commented
/lgtm

2022-04-06 12:54 UTC, 2uasimojo commented
This won’t pass lint until the reported issues are fixed. A couple of them would require either renaming variables or adding ignore comments for the linter; which is preferred?

2022-05-18 14:19 UTC, 2uasimojo commented
Closing in favor of #698 and #699

2022-05-18 14:19 UTC, closed without merging

2022-05-18 14:20 UTC, dastergon commented
Closing this, in favor of #699 & #698